### ISSUE TITLE
Audio player on entrypage dissapears on mobile

### ISSUE THREAD

**Issue by yannvanhalewyn** [woutervuden/sputnik9design#1]
Onder een viewport van 500px ongeveer verdwijnt de audio speler.

**Comment by yannvanhalewyn** [comment]
Komt volgens mij van de bootstrap "sidebar" class [hier](https://github.com/woutervuden/sputnik9design/blob/master/entrypage2.html#L56)! Misschien toch van de grid system uitgaan. Of een nieuwe class maken die een 'aside' like feel heeft in browsers, een een sticky footer vanaf 500px.

**Comment by woutervuden** [comment]
Is now the default behavior!
