### ISSUE TITLE
Markup

### ISSUE THREAD

**Issue by yannvanhalewyn** [woutervuden/sputnik9design#3]
Hier komt een lijstje van markup die wat verbetering nodig heeft:
- `<H>` element bestaat niet. Kijk [hier](https://github.com/woutervuden/sputnik9design/blob/master/entrypage2.html#L61). Ik kan tevens later geen html elementen genereren die niet bestaan. Misschien is `<h4>` wel van toepassing.

**Comment by woutervuden** [comment]
Done!
