### ISSUE TITLE
Positioning of "Members"

### ISSUE THREAD

**Issue by yannvanhalewyn** [woutervuden/sputnik9design#4]
Op de premiumpage staan de members onder elkaar gelijst onder de tittel. Dit zorgt dus op kleinere laptop schermen dat de videospeler niet helemaal te zien is. Ook is ziet het er een beetje uit balans uit vind ik zelf. Een idee is om misschien de members van links naar rechts te plaatsen. Er zou dan bijvoorbeeld een headshot foto'tje in een cirkel kunnen staan met daaronder de naam van de artiest en het instrument dat hij bespeelt. Thoughts?

**Comment by yannvanhalewyn** [comment]
Hier is trouwens mijn idee uitgevoerd op [codepen](http://codepen.io/yannvanhalewyn/pen/YweGbG).

**Comment by woutervuden** [comment]
What a great idea Yann! You're such an inspiration. Thank you and god bless!

**Comment by woutervuden** [comment]
Done btw :+1:
